### ISSUE TITLE
firewall config bootstrap

### ISSUE THREAD

**Issue by storrgie** [epiphyte/servers#2]
Totally didn't notice this was already in the bootstrap...

So to save face I'd like to turn this into: should we also clean up the default `/etc/iptables` folder (remove `empty.rules` and `simple_firewall.rules`)?

**Comment by enckse** [comment]
we could clean it up but I'd prefer not to do it via the bootstrap script, besides those are "arch provided" and I would rather not jerk around with them unless we need to
