### ISSUE TITLE
linuxfirmware likely not necessary

### ISSUE THREAD

**Issue by storrgie** [epiphyte/servers#5]
I think since we are ignoring linux in the pacstrap-container script it doesn't pull in [linux-firmware](https://www.archlinux.org/packages/core/any/linux-firmware/). It's also `linux-firmware`, but since it doesn't get dep'ed by another package the ignore doesn't hit.

**Comment by enckse** [comment]
I will fix the name, I'd rather leave it (in case something does change and pull it)
